config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  get '/all_users/:id', :controller=>'users', :action=>'show'

  resources :cities do
    get '/cities/', :controller=>'cities', :action=>'index'
    get '/cities/:id', :controller=>'cities', :action=>'show'
    get '/cities/:id/edit', :controller=>'cities', :action=>'edit'
    get '/cities/new', :controller=>'cities', :action=>'create'
  end

end

app/models/city.rb
class City < ActiveRecord::Base
  #devise :database_authenticatable, :registerable,
  #      :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :age, :email, :password) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :age, :email, :password, :current_password, :is_female, :date_of_birth) }
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  def index
    @cities = City.all.paginate(page: params[:page], per_page: 5)
  end

  def show
    @city = City.find(params[:id])
  end

  def new
    @city = City.new
  end

  def search

  end

  def edit

  end

  def details

  end

  def create
    @city = City.new(city_params)
    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'Poprawnie utworzony.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'Zaktualizowano poprawnie.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to '/cities', notice: 'Wpis został usunięty.' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_city
    @city = City.find(params[:id])
  end

  # Never trust parameters from internet :-)
  def city_params
    params.require(:city).permit(:name, :short_name)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
      @users = User.all
    end

    def show
      @user = User.find(params[:id])
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
  end

  def update

  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<td><%= link_to city.name, city %></td>
<td><%= link_to city.short_name, city %></td>

app/views/cities/_form.html.erb
<%= form_for @city do |f| %>
    <div>
      <%= f.label :name, class: "new-formlabel" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div>
      <%= f.label :short_name, class: "new-formlabel" %>
      <%= f.text_field :short_name, class: "form-control" %>
    </div>
    <br />
    <div>
      <%= link_to 'Back', cities_path, class: "btn btn-primary" %>
      <%= f.submit :value => "Zapisz", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/cities/edit.html.erb
<div>
  <h1>Edycja</h1>

  <%= render 'form' %>
  <br />
  <%= link_to 'Podgląd', @city %>

</div>

app/views/cities/index.html.erb
        <% @cities.each do |city| %>
            <div>
              <p><%= render city %> -- <%= link_to 'delete', city, method: :delete, data: { confirm: 'Wykasować z bazy danych ?' } %></p>
            </div>
            <br />
        <% end %>
        <div class="pagination">
          <%= will_paginate @cities, :class => 'page' %>
        </div>
        <div><%= link_to 'Create City', new_city_path(@city) %></div>

app/views/cities/new.html.erb
        <div>

          <h1>New city ?</h1><br />

          <%= render 'form' %>

        </div>

app/views/cities/show.html.erb
  <p>
    <b>Name:</b> <%= @city.name if @city.name %></p>
  </p>
  <p>
    <b>Short Name:</b> <%= @city.short_name if @city.short_name %></p>
  </p>
<br />
  <br />
  <div><%= link_to 'Edit City', edit_city_path(@city) %> || <%= link_to 'City Home', :controller=>'cities', :action=>'index' %></div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
         <li><%= link_to 'Posts', '#' %></li>
        <% if current_user %>
            <li><%= link_to 'Cities', :controller=>'cities', :action=>'index' %></li>
            <li><%= link_to 'Edit Profile',edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.age, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Age: <%= @user.age if @user.age %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<% if user_signed_in? %>
<h3 id="user-welcome" data-name="<%= current_user.name %>">Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>
<% else if !user_signed_in? %>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>
    <% end %>
<% end %>